site_name: NRV docs

theme: readthedocs

nav:
  - Home: index.md
  # - About NRV: about-NRV.md
  - Projects:
    - MIPI2PCIE_AXIS : projects/MIPI2PCIE_AXIS.md
  - MANUAL:
    - DVS-FMC Board Pinmap : datasheet/DVS_FMC.md
    - DVS-MIPI Register Set File: register/DVS_MIPI.md