### Site metadata ###

site_name: NRV docs
site_description: NRV HW/SW resources & documentations
site_url: https://nrvcorp.github.io/docs/

repo_url: https://nrvcorp.github.io/docs/
edit_uri: edit/master/docs/docs

### Build settings ###

theme: readthedocs

nav:
  - Home: index.md
  - About MkDocs: about-mkdocs.md
  - Tutorial:
      - TL;DR: tutorial/tldr.md
      - Installation: tutorial/installation.md
      - Set up project: tutorial/setup-project.md
      - Advanced: tutorial/advanced.md
      - Usage: tutorial/usage.md
      - Deploy: tutorial/deploy.md
